-- GENERATED by scripts/build-phase-16-16a-rollback-validation.mjs. Do not edit.
-- Migration: supabase/migrations/20260926210000_phase_16_16_quarantine_payload_retention.sql
-- Migration SHA-256: 33706d5006de9f9d7e900b51296598ba76638da3105acac594f26d1fa0834bc2
-- Attachment SHA-256: 02117fdab48cb77c95c7c642ee0be59c89672e29c0e3ee3eeffa8d02c6f21da0
-- ROLLBACK-ONLY production compatibility validation for Phase 16.16A.
begin;
set local lock_timeout = '3s';
set local statement_timeout = '60s';
set local idle_in_transaction_session_timeout = '120s';
set local search_path = extensions, public, auth;

-- Pre-migration state, captured inside the transaction.
create temporary table v16a_before on commit drop as select
  (select md5(p.prosrc) from pg_proc p
    where p.oid = 'public.record_cpsc_identity_observation(text,text,text,text,text,date,text,timestamptz,text)'::regprocedure) as legacy_gate_md5,
  (select count(*) from private.cpsc_identity_observations) as observations,
  (select md5(string_agg(o::text, '|' order by o.id)) from private.cpsc_identity_observations o) as observations_md5,
  (select md5(string_agg(i::text, '|' order by i.id)) from private.cpsc_source_identities i) as identities_md5,
  (select md5(string_agg(a::text, '|' order by a.id)) from private.cpsc_source_aliases a) as aliases_md5,
  (select md5(string_agg(r::text, '|' order by r.id)) from private.cpsc_api_revisions r) as api_revisions_md5,
  (select md5(string_agg(n::text, '|' order by n.id)) from public.recall_notices n) as notices_md5,
  (select md5(string_agg(s::text, '|' order by s.source_id)) from private.recall_source_sync_state s) as sync_md5,
  private.cpsc_historical_rows_digest((select id from public.recall_sources where source_key = 'cpsc')) as historical_digest;
create temporary table v16a_six (api text, num text, hash text) on commit drop;
insert into v16a_six values
  ('10969','26749','1316efd47ec33bf7fc3029e985bd6d1049efbf4bcf450e3ea4599bef2aa7e23a'),
  ('10965','26753','316823508cb771a7d86efaffbf04b8cc678703d59c34ae78ab29e5a594d18de0'),
  ('10967','26754','5af2405f874ee90f9819eca708f6be60123abee3566bcdcd87b4f75df4f2e104'),
  ('10968','26756','a300928462e2324ed88b30891146b0e8cd23a9417675a480d86dd20847b09cf1'),
  ('10966','26763','2ead4847dfed00d4d1280ccfc6493a1fe176dbb6a96c285faef0736b6e440117'),
  ('10970','26766','b4a8d7501f9a5ccd37fc2cfa74429a1a02a01134df7eb234aba23d7a44000731');

-- ===== BEGIN exact migration body =====

-- ===========================================================================
-- Hash contract `cpsc-canonical-json-sha256/v1`: SHA-256 over the UTF-8 bytes of
-- canonical JSON. Object keys are sorted by code point (C collation) at every
-- depth, arrays keep their order, there is no whitespace, strings use PostgreSQL
-- JSON escaping, and numbers use their jsonb text. It produces the same text as
-- 16.12's private.cpsc_canonical_json using only immutable operations (jsonb
-- output and keyvalue() share PostgreSQL's escape_json), so a generated column can
-- compute it. It equals the worker's sourcePayloadSha256 on every captured payload.
-- There is no raw-byte hash: the CPSC API returns one array per window, so a
-- single record has no stable transport byte range to hash.
-- ===========================================================================
create function private.cpsc_canonical_json_v1(p_value jsonb)
returns text language plpgsql immutable set search_path = '' as $$
declare v_out text;
begin
  case jsonb_typeof(p_value)
    when 'object' then
      select '{' || coalesce(string_agg((pair -> 'key')::text || ':' ||
          private.cpsc_canonical_json_v1(pair -> 'value'), ','
          order by pair ->> 'key' collate "C"), '') || '}'
        into v_out from jsonb_path_query(p_value, '$.keyvalue()') pair;
      return v_out;
    when 'array' then
      select '[' || coalesce(string_agg(private.cpsc_canonical_json_v1(item.value), ','
          order by item.ordinality), '') || ']'
        into v_out from jsonb_array_elements(p_value) with ordinality item;
      return v_out;
    else
      -- Scalars (string, number, boolean, null) as jsonb prints them.
      return p_value::text;
  end case;
end;
$$;

create function private.cpsc_payload_sha256_v1(p_payload jsonb)
returns text language sql immutable set search_path = '' as $$
  select encode(sha256(convert_to(private.cpsc_canonical_json_v1(p_payload), 'UTF8')), 'hex');
$$;

-- ===========================================================================
-- Source revisions: one row per distinct authoritative CPSC API payload.
-- The key is computed by the database from the stored payload, so a caller can
-- never store a payload under a hash that does not belong to it. A changed payload
-- has a different hash and becomes a new row. No row is ever updated or deleted.
-- Public CPSC source data only: no owned-product, user, or credential data.
-- ===========================================================================
create table private.cpsc_observation_payloads (
  canonical_payload_sha256 text
    generated always as (private.cpsc_payload_sha256_v1(payload)) stored primary key,
  revision_seq bigint generated always as identity unique,
  payload jsonb not null,
  upstream_api_id text generated always as (payload ->> 'RecallID') stored,
  official_recall_number text
    generated always as (private.cpsc_payload_recall_number(payload)) stored,
  canonical_payload_bytes integer
    generated always as (octet_length(private.cpsc_canonical_json_v1(payload))) stored,
  hash_contract text not null default 'cpsc-canonical-json-sha256/v1'
    check (hash_contract = 'cpsc-canonical-json-sha256/v1'),
  payload_contract text not null default 'cpsc-recall-api-record/v1'
    check (payload_contract = 'cpsc-recall-api-record/v1'),
  recorded_via text not null
    check (recorded_via in ('worker_observation', 'captured_payload_attachment')),
  provenance text not null check (btrim(provenance) <> '' and length(provenance) <= 500),
  recorded_at timestamptz not null default now(),
  constraint cpsc_observation_payloads_object check (jsonb_typeof(payload) = 'object'),
  constraint cpsc_observation_payloads_size check (canonical_payload_bytes <= 262144),
  constraint cpsc_observation_payloads_api_id check (
    jsonb_typeof(payload -> 'RecallID') in ('number', 'string')
    and upstream_api_id ~ '^[0-9]{1,18}$'),
  constraint cpsc_observation_payloads_recall_number check (official_recall_number is not null),
  constraint cpsc_observation_payloads_url check (
    jsonb_typeof(payload -> 'URL') = 'string'
    and private.cpsc_canonical_url(payload ->> 'URL') is not null),
  constraint cpsc_observation_payloads_title check (
    jsonb_typeof(payload -> 'Title') = 'string' and btrim(payload ->> 'Title') <> ''),
  constraint cpsc_observation_payloads_recall_date check (
    jsonb_typeof(payload -> 'RecallDate') = 'string'
    and payload ->> 'RecallDate' ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}')
);
create index cpsc_observation_payloads_lineage_idx
  on private.cpsc_observation_payloads(upstream_api_id, official_recall_number, revision_seq);
alter table private.cpsc_observation_payloads enable row level security;
create trigger cpsc_observation_payloads_append_only
  before update or delete on private.cpsc_observation_payloads
  for each row execute function private.cpsc_append_only();
create trigger cpsc_observation_payloads_no_truncate
  before truncate on private.cpsc_observation_payloads
  for each statement execute function private.cpsc_append_only();

-- Supports retention joins and quarantine replay lookups.
create index cpsc_identity_observations_payload_idx
  on private.cpsc_identity_observations(payload_hash);

-- ===========================================================================
-- Repeat sightings. Compact counters live beside the append-only observation,
-- never in it: the observation (the review item) is written once.
-- ===========================================================================
create table private.cpsc_observation_sightings (
  observation_id uuid primary key
    references private.cpsc_identity_observations(id) on delete restrict,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  seen_count bigint not null check (seen_count >= 1),
  last_provenance text not null
    check (btrim(last_provenance) <> '' and length(last_provenance) <= 200),
  check (last_seen_at >= first_seen_at)
);
alter table private.cpsc_observation_sightings enable row level security;

create function private.cpsc_guard_sighting_update()
returns trigger language plpgsql set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'CPSC sightings are never deleted' using errcode = '42501';
  end if;
  if new.observation_id <> old.observation_id or new.first_seen_at <> old.first_seen_at
    or new.seen_count <= old.seen_count or new.last_seen_at < old.last_seen_at then
    raise exception 'CPSC sightings only move forward' using errcode = '42501';
  end if;
  return new;
end;
$$;
create trigger cpsc_guard_sighting_update
  before update or delete on private.cpsc_observation_sightings
  for each row execute function private.cpsc_guard_sighting_update();
create trigger cpsc_observation_sightings_no_truncate
  before truncate on private.cpsc_observation_sightings
  for each statement execute function private.cpsc_append_only();

-- ===========================================================================
-- Retention is derived, never asserted: an observation's payload is retained iff
-- a stored source revision has the same database-computed hash AND the same API
-- ID and recall number. Everything else is `legacy_hash_only`, including every
-- observation recorded before this migration (none is rewritten or fabricated).
-- ===========================================================================
create view private.cpsc_observation_payload_retention
with (security_invoker = true) as
select o.id as observation_id, o.observation_seq, o.upstream_api_id,
  o.official_recall_number, o.resolution, o.decision_class, o.payload_hash,
  o.observed_at, payload.recorded_via, payload.revision_seq,
  case when payload.canonical_payload_sha256 is null then 'legacy_hash_only'
    else 'retained' end as payload_retention
from private.cpsc_identity_observations o
left join private.cpsc_observation_payloads payload
  on payload.canonical_payload_sha256 = o.payload_hash
  and payload.upstream_api_id = o.upstream_api_id
  and payload.official_recall_number = o.official_recall_number;

-- Watermark rule: the CPSC watermark may advance only while every quarantined
-- observation retains its reviewable source payload. Resolved observations are
-- accounted for by canonical identity state. A hash-only quarantine (from any
-- path, legacy or not, reconciled or not) is never watermark-safe.
create function private.cpsc_watermark_safety()
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'contract', 'cpsc-watermark-safety/v1',
    'safe', count(*) filter (where r.payload_retention <> 'retained') = 0,
    'quarantined', count(*),
    'retained', count(*) filter (where r.payload_retention = 'retained'),
    'legacyHashOnly', count(*) filter (where r.payload_retention = 'legacy_hash_only'),
    'unaccounted', coalesce(jsonb_agg(jsonb_build_object(
        'observationId', r.observation_id, 'apiId', r.upstream_api_id,
        'recallNumber', r.official_recall_number, 'payloadHash', r.payload_hash,
        'decisionClass', r.decision_class)
        order by r.observation_seq) filter (where r.payload_retention <> 'retained'), '[]'::jsonb))
  from private.cpsc_observation_payload_retention r
  where r.resolution = 'quarantined';
$$;

create function private.cpsc_guard_watermark_advance()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_safety jsonb;
begin
  if new.watermark is null
    or (tg_op = 'UPDATE' and new.watermark is not distinct from old.watermark) then
    return new;
  end if;
  if not exists (select 1 from public.recall_sources source
    where source.id = new.source_id and source.source_key = 'cpsc') then
    return new;
  end if;
  v_safety := private.cpsc_watermark_safety();
  if not coalesce((v_safety ->> 'safe')::boolean, false) then
    raise exception 'CPSC watermark cannot advance: % quarantined observation(s) lack a retained source payload',
      jsonb_array_length(v_safety -> 'unaccounted') using errcode = '23514';
  end if;
  return new;
end;
$$;
create trigger cpsc_guard_watermark_advance
  before insert or update of watermark on private.recall_source_sync_state
  for each row execute function private.cpsc_guard_watermark_advance();

-- ===========================================================================
-- Worker RPC: the identity decision is made by the unchanged 16.11 gate
-- (public.record_cpsc_identity_observation), so there is one decision matrix.
-- This wrapper verifies and stores the payload first, then replays an identical
-- quarantine onto its existing review item instead of appending a new one.
-- It cannot reconcile, review, create criteria, or invalidate decisions.
-- ===========================================================================
create function public.record_cpsc_retained_observation(
  p_api_id text, p_recall_number text, p_observed_url text,
  p_canonical_url text, p_title text, p_publication_date date,
  p_payload_hash text, p_observed_at timestamptz, p_provenance text,
  p_raw_payload jsonb
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_hash text;
  v_payload_recorded boolean;
  v_result jsonb;
  v_prior private.cpsc_identity_observations%rowtype;
  v_seen_count bigint;
begin
  if not private.cpsc_is_worker() then
    raise exception 'CPSC worker authorization required' using errcode = '42501';
  end if;
  -- Cheap bound before canonicalizing, then the exact bound on the hashed bytes.
  if p_raw_payload is null or jsonb_typeof(p_raw_payload) <> 'object'
    or pg_column_size(p_raw_payload) > 1048576
    or octet_length(private.cpsc_canonical_json_v1(p_raw_payload)) > 262144 then
    raise exception 'Invalid CPSC source payload' using errcode = '22023';
  end if;
  v_hash := private.cpsc_payload_sha256_v1(p_raw_payload);
  if p_payload_hash is distinct from v_hash then
    raise exception 'CPSC payload hash does not match its payload' using errcode = '22023';
  end if;
  if p_raw_payload ->> 'RecallID' is distinct from p_api_id
    or private.cpsc_payload_recall_number(p_raw_payload) is distinct from p_recall_number
    or btrim(p_raw_payload ->> 'URL') is distinct from p_observed_url
    or left(p_raw_payload ->> 'RecallDate', 10)
      is distinct from to_char(p_publication_date, 'YYYY-MM-DD')
    or coalesce(strpos(p_raw_payload ->> 'Title', p_title), 0) = 0 then
    raise exception 'CPSC payload does not match its observation' using errcode = '22023';
  end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('cpsc:identity-decisions'));

  insert into private.cpsc_observation_payloads (payload, recorded_via, provenance)
  values (p_raw_payload, 'worker_observation', p_provenance)
  on conflict (canonical_payload_sha256) do nothing;
  v_payload_recorded := found;

  begin
    v_result := public.record_cpsc_identity_observation(p_api_id, p_recall_number,
      p_observed_url, p_canonical_url, p_title, p_publication_date, v_hash,
      p_observed_at, p_provenance);
    if v_result ->> 'status' = 'quarantined' then
      select o.* into v_prior from private.cpsc_identity_observations o
      where o.id <> (v_result ->> 'observationId')::uuid
        and o.resolution = 'quarantined' and o.payload_hash = v_hash
        and o.upstream_api_id = p_api_id and o.official_recall_number = p_recall_number
        and o.observed_url = p_observed_url and o.canonical_url = p_canonical_url
        and o.title = p_title and o.publication_date = p_publication_date
        and o.decision_class = v_result ->> 'decisionClass'
        and o.reason = v_result ->> 'reason'
      order by o.observation_seq limit 1;
      if v_prior.id is not null then
        -- Same source revision, same decision: undo the duplicate review item.
        raise exception 'replayed CPSC quarantine' using errcode = 'RCQ01';
      end if;
    end if;
  exception when sqlstate 'RCQ01' then
    null;
  end;

  if not exists (select 1 from private.cpsc_observation_payloads payload
    where payload.canonical_payload_sha256 = v_hash and payload.upstream_api_id = p_api_id
      and payload.official_recall_number = p_recall_number) then
    raise exception 'CPSC source payload was not retained';
  end if;

  if v_prior.id is not null then
    insert into private.cpsc_observation_sightings as sighting (
      observation_id, first_seen_at, last_seen_at, seen_count, last_provenance
    ) values (
      v_prior.id, v_prior.observed_at, greatest(v_prior.observed_at, p_observed_at), 2,
      p_provenance
    ) on conflict (observation_id) do update
      set last_seen_at = greatest(sighting.last_seen_at, excluded.last_seen_at),
        seen_count = sighting.seen_count + 1, last_provenance = excluded.last_provenance
    returning sighting.seen_count into v_seen_count;
    return jsonb_build_object('status', 'quarantined', 'observationId', v_prior.id,
      'reason', v_prior.reason, 'decisionClass', v_prior.decision_class,
      'replayed', true, 'seenCount', v_seen_count, 'payloadSha256', v_hash,
      'payloadRetention', 'retained', 'payloadRecorded', v_payload_recorded);
  end if;
  if v_result ->> 'status' = 'quarantined' then
    insert into private.cpsc_observation_sightings (
      observation_id, first_seen_at, last_seen_at, seen_count, last_provenance
    ) values ((v_result ->> 'observationId')::uuid, p_observed_at, p_observed_at, 1, p_provenance);
    return v_result || jsonb_build_object('replayed', false, 'seenCount', 1,
      'payloadSha256', v_hash, 'payloadRetention', 'retained',
      'payloadRecorded', v_payload_recorded);
  end if;
  return v_result || jsonb_build_object('payloadSha256', v_hash,
    'payloadRetention', 'retained', 'payloadRecorded', v_payload_recorded);
end;
$$;

-- ===========================================================================
-- Reconciliation packet: 16.11 fields unchanged, plus the stored source payload,
-- its database re-verified hash, sightings, and the source-revision lineage for
-- the same API ID and recall number, so review never needs a CPSC refetch.
-- ===========================================================================
create or replace function private.cpsc_quarantine_evidence(p_observation_id uuid)
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'observationId', o.id,
    'incomingApiId', o.upstream_api_id,
    'officialRecallNumber', o.official_recall_number,
    'observedUrl', o.observed_url,
    'canonicalUrl', o.canonical_url,
    'title', o.title,
    'publicationDate', o.publication_date,
    'payloadHash', o.payload_hash,
    'observedAt', o.observed_at,
    'provenance', o.provenance,
    'resolution', o.resolution,
    'reason', o.reason,
    'decisionClass', o.decision_class,
    'currentIdentity', (
      select jsonb_build_object('identityId', i.id,
        'officialRecallNumber', i.official_recall_number, 'canonicalUrl', i.canonical_url,
        'canonicalNoticeId', i.canonical_notice_id, 'status', i.identity_status,
        'linkedNotices', coalesce((select jsonb_agg(jsonb_build_object(
            'noticeId', n.id, 'externalId', n.external_id, 'title', n.title,
            'officialUrl', n.official_url, 'recallDate', n.recall_date) order by n.external_id)
          from private.cpsc_notice_identity_links link
          join public.recall_notices n on n.id = link.notice_id
          where link.identity_id = i.id), '[]'::jsonb))
      from private.cpsc_source_identities i
      where i.official_recall_number = o.official_recall_number),
    'conflictingAliases', coalesce((select jsonb_agg(jsonb_build_object(
        'identityId', a.identity_id, 'officialRecallNumber', i.official_recall_number,
        'canonicalUrl', i.canonical_url, 'aliasKind', a.alias_kind,
        'aliasValue', a.alias_value, 'noticeId', a.notice_id, 'provenance', a.provenance,
        'humanConfirmed', a.reconciliation_id is not null)
        order by i.official_recall_number, a.provenance)
      from private.cpsc_source_aliases a
      join private.cpsc_source_identities i on i.id = a.identity_id
      where (a.alias_kind = 'api_id' and a.alias_value = o.upstream_api_id)
        or (a.alias_kind = 'official_url'
          and private.cpsc_canonical_url(a.alias_value) = o.canonical_url)), '[]'::jsonb),
    'historicalNotices', coalesce((select jsonb_agg(jsonb_build_object(
        'noticeId', n.id, 'externalId', n.external_id, 'title', n.title,
        'officialUrl', n.official_url, 'recallDate', n.recall_date,
        'linkedIdentityId', link.identity_id) order by n.external_id)
      from public.recall_notices n
      join public.recall_sources s on s.id = n.source_id and s.source_key = 'cpsc'
      left join private.cpsc_notice_identity_links link on link.notice_id = n.id
      where n.external_id = o.upstream_api_id
        or private.cpsc_canonical_url(n.official_url) = o.canonical_url
        or regexp_replace(coalesce(n.raw_payload->>'RecallNumber', ''),
          '^([0-9]{2})-?([0-9]{3})$', '\1\2') = o.official_recall_number), '[]'::jsonb),
    'priorDecisions', coalesce((select jsonb_agg(jsonb_build_object(
        'decision', r.decision, 'reviewerUserId', r.reviewer_user_id,
        'identityId', r.identity_id, 'rationale', r.rationale, 'decidedAt', r.decided_at)
        order by r.decision_seq)
      from private.cpsc_identity_reconciliations r where r.observation_id = o.id), '[]'::jsonb),
    'payloadRetention', case when source_revision.canonical_payload_sha256 is null
      then 'legacy_hash_only' else 'retained' end,
    'sourceRevision', case when source_revision.canonical_payload_sha256 is not null then
      jsonb_build_object(
        'payloadSha256', source_revision.canonical_payload_sha256,
        'hashVerified', source_revision.canonical_payload_sha256
          = private.cpsc_payload_sha256_v1(source_revision.payload),
        'hashContract', source_revision.hash_contract,
        'payloadContract', source_revision.payload_contract,
        'revisionSeq', source_revision.revision_seq,
        'recordedVia', source_revision.recorded_via,
        'recordedAt', source_revision.recorded_at,
        'provenance', source_revision.provenance,
        'payloadBytes', source_revision.canonical_payload_bytes,
        'payload', source_revision.payload) end,
    'sightings', coalesce((select jsonb_build_object('firstSeenAt', s.first_seen_at,
        'lastSeenAt', s.last_seen_at, 'seenCount', s.seen_count)
      from private.cpsc_observation_sightings s where s.observation_id = o.id),
      jsonb_build_object('firstSeenAt', o.observed_at, 'lastSeenAt', o.observed_at,
        'seenCount', 1)),
    'sourceRevisionLineage', coalesce((select jsonb_agg(jsonb_build_object(
        'payloadSha256', p.canonical_payload_sha256, 'revisionSeq', p.revision_seq,
        'recordedVia', p.recorded_via, 'recordedAt', p.recorded_at,
        'thisObservation', p.canonical_payload_sha256 = o.payload_hash,
        'quarantinedObservationIds', coalesce((select jsonb_agg(q.id order by q.observation_seq)
          from private.cpsc_identity_observations q
          where q.resolution = 'quarantined' and q.payload_hash = p.canonical_payload_sha256
            and q.upstream_api_id = p.upstream_api_id
            and q.official_recall_number = p.official_recall_number), '[]'::jsonb))
        order by p.revision_seq)
      from private.cpsc_observation_payloads p
      where p.upstream_api_id = o.upstream_api_id
        and p.official_recall_number = o.official_recall_number), '[]'::jsonb))
  from private.cpsc_identity_observations o
  left join private.cpsc_observation_payloads source_revision
    on source_revision.canonical_payload_sha256 = o.payload_hash
    and source_revision.upstream_api_id = o.upstream_api_id
    and source_revision.official_recall_number = o.official_recall_number
  where o.id = p_observation_id;
$$;

-- ===========================================================================
-- Bounded attachment of captured payloads to EXISTING quarantined observations
-- (owner-only; never granted, never invoked here). An item is accepted only if
-- its database-computed hash equals the hash that a quarantined observation
-- already recorded for the same API ID and recall number, so it can only supply
-- the exact preimage of recorded evidence. It never writes an observation,
-- identity, alias, notice, reconciliation, or criterion. Idempotent; all-or-nothing.
-- ===========================================================================
create function private.cpsc_attach_captured_payloads(p_attachment jsonb, p_execute boolean)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_item jsonb;
  v_hash text;
  v_observations jsonb;
  v_present boolean;
  v_attached integer := 0;
  v_already integer := 0;
  v_report jsonb := '[]'::jsonb;
  v_provenance text;
begin
  if p_execute is null or jsonb_typeof(p_attachment) is distinct from 'object'
    or p_attachment ->> 'attachmentVersion' is distinct from 'phase-16.16a-captured-payload-attachment-v1'
    or p_attachment ->> 'apiRoot' is distinct from 'https://www.saferproducts.gov/RestWebServices/Recall'
    or coalesce(p_attachment ->> 'captureSha256', '') !~ '^[0-9a-f]{64}$'
    or coalesce(p_attachment ->> 'capturedAtUtc', '') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T'
    or jsonb_typeof(p_attachment -> 'items') is distinct from 'array'
    or jsonb_array_length(p_attachment -> 'items') not between 1 and 50
    or (select count(distinct value ->> 'payloadSha256')
      from jsonb_array_elements(p_attachment -> 'items')) <> jsonb_array_length(p_attachment -> 'items') then
    raise exception 'Invalid captured payload attachment' using errcode = '22023';
  end if;
  v_provenance := 'Phase 16.16A captured payload attachment; capture sha256 '
    || (p_attachment ->> 'captureSha256') || ' at ' || (p_attachment ->> 'capturedAtUtc');
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('cpsc:identity-decisions'));

  for v_item in select value from jsonb_array_elements(p_attachment -> 'items') order by value ->> 'recallNumber'
  loop
    if jsonb_typeof(v_item) is distinct from 'object'
      or (select count(*) from jsonb_object_keys(v_item)) <> 4
      or jsonb_typeof(v_item -> 'payload') is distinct from 'object'
      or coalesce(v_item ->> 'apiId', '') !~ '^[0-9]{1,18}$'
      or coalesce(v_item ->> 'recallNumber', '') !~ '^[0-9]{5}$'
      or octet_length(private.cpsc_canonical_json_v1(v_item -> 'payload')) > 262144 then
      raise exception 'Invalid captured payload item' using errcode = '22023';
    end if;
    v_hash := private.cpsc_payload_sha256_v1(v_item -> 'payload');
    if v_hash is distinct from v_item ->> 'payloadSha256' then
      raise exception 'Captured payload hash mismatch for recall %', v_item ->> 'recallNumber'
        using errcode = '22023';
    end if;
    if v_item -> 'payload' ->> 'RecallID' is distinct from v_item ->> 'apiId'
      or private.cpsc_payload_recall_number(v_item -> 'payload') is distinct from v_item ->> 'recallNumber' then
      raise exception 'Captured payload identity mismatch for recall %', v_item ->> 'recallNumber'
        using errcode = '22023';
    end if;
    select jsonb_agg(o.id order by o.observation_seq) into v_observations
    from private.cpsc_identity_observations o
    where o.resolution = 'quarantined' and o.payload_hash = v_hash
      and o.upstream_api_id = v_item ->> 'apiId'
      and o.official_recall_number = v_item ->> 'recallNumber';
    if v_observations is null then
      raise exception 'No quarantined observation recorded payload % for recall %',
        v_hash, v_item ->> 'recallNumber' using errcode = '22023';
    end if;
    v_present := exists (select 1 from private.cpsc_observation_payloads p
      where p.canonical_payload_sha256 = v_hash);
    if p_execute and not v_present then
      insert into private.cpsc_observation_payloads (payload, recorded_via, provenance)
      values (v_item -> 'payload', 'captured_payload_attachment', v_provenance);
    end if;
    if v_present then v_already := v_already + 1; else v_attached := v_attached + 1; end if;
    v_report := v_report || jsonb_build_object('recallNumber', v_item ->> 'recallNumber',
      'apiId', v_item ->> 'apiId', 'payloadSha256', v_hash,
      'quarantinedObservationIds', v_observations,
      'action', case when v_present then 'already_retained'
        when p_execute then 'attached' else 'would_attach' end);
  end loop;
  return jsonb_build_object('execute', p_execute, 'items', jsonb_array_length(v_report),
    'attached', case when p_execute then v_attached else 0 end,
    'wouldAttach', case when p_execute then 0 else v_attached end,
    'alreadyRetained', v_already, 'report', v_report,
    'watermarkSafety', private.cpsc_watermark_safety());
end;
$$;

-- ===========================================================================
-- Privilege boundary. New tables and the view are private with RLS and no
-- policies; only SECURITY DEFINER functions touch them. The worker gets exactly
-- one new RPC. The reconciliation packet keeps its 16.12 capability gate.
-- ===========================================================================
revoke all on private.cpsc_observation_payloads, private.cpsc_observation_sightings,
  private.cpsc_observation_payload_retention
  from public, anon, authenticated, service_role;
revoke all on function
  private.cpsc_canonical_json_v1(jsonb),
  private.cpsc_payload_sha256_v1(jsonb),
  private.cpsc_guard_sighting_update(),
  private.cpsc_watermark_safety(),
  private.cpsc_guard_watermark_advance(),
  private.cpsc_attach_captured_payloads(jsonb, boolean)
  from public, anon, authenticated, service_role;
revoke all on function public.record_cpsc_retained_observation(
  text, text, text, text, text, date, text, timestamptz, text, jsonb)
  from public, anon, authenticated, service_role;
grant execute on function public.record_cpsc_retained_observation(
  text, text, text, text, text, date, text, timestamptz, text, jsonb)
  to service_role;

-- ===== END exact migration body =====

select extensions.no_plan();

-- Schema and privileges on the real database.
select extensions.ok(to_regclass(t) is not null, format('%s created', t))
  from unnest(array['private.cpsc_observation_payloads','private.cpsc_observation_sightings',
    'private.cpsc_observation_payload_retention']) t;
select extensions.ok(c.relrowsecurity, format('RLS on %s', c.relname))
  from pg_class c where c.oid in ('private.cpsc_observation_payloads'::regclass,
    'private.cpsc_observation_sightings'::regclass);
select extensions.ok(has_function_privilege('service_role',
    'public.record_cpsc_retained_observation(text,text,text,text,text,date,text,timestamptz,text,jsonb)','EXECUTE')
  and not has_function_privilege('anon',
    'public.record_cpsc_retained_observation(text,text,text,text,text,date,text,timestamptz,text,jsonb)','EXECUTE')
  and not has_function_privilege('authenticated',
    'public.record_cpsc_retained_observation(text,text,text,text,text,date,text,timestamptz,text,jsonb)','EXECUTE'),
  'new worker RPC is service-role only');
select extensions.ok(not has_table_privilege(r, t, 'SELECT') and not has_table_privilege(r, t, 'INSERT'),
  format('%s cannot read or write %s', r, t))
  from unnest(array['anon','authenticated','service_role']) r,
    unnest(array['private.cpsc_observation_payloads','private.cpsc_observation_sightings',
      'private.cpsc_observation_payload_retention']) t;
select extensions.ok(not has_function_privilege(r, f, 'EXECUTE'), format('%s cannot execute %s', r, f))
  from unnest(array['anon','authenticated','service_role']) r,
    unnest(array['private.cpsc_attach_captured_payloads(jsonb,boolean)','private.cpsc_watermark_safety()',
      'private.cpsc_quarantine_evidence(uuid)']) f;
select extensions.ok(not has_function_privilege('service_role', f, 'EXECUTE'), format('worker cannot execute %s', f))
  from unnest(array['public.get_cpsc_quarantine_packet(uuid)',
    'public.reconcile_cpsc_quarantined_observation(uuid,text,text)']) f;
select extensions.is((select md5(p.prosrc) from pg_proc p
    where p.oid = 'public.record_cpsc_identity_observation(text,text,text,text,text,date,text,timestamptz,text)'::regprocedure),
  (select legacy_gate_md5 from v16a_before), 'legacy 9-argument gate body is unchanged');
select extensions.ok(has_function_privilege('service_role',
    'public.record_cpsc_identity_observation(text,text,text,text,text,date,text,timestamptz,text)','EXECUTE'),
  'legacy gate keeps its worker grant (deployed v3 worker stays compatible)');

-- The migration rewrites no production row.
select extensions.ok((select observations from v16a_before) = (select count(*) from private.cpsc_identity_observations)
  and (select observations_md5 from v16a_before) = (select md5(string_agg(o::text, '|' order by o.id)) from private.cpsc_identity_observations o),
  'observation rows unchanged by the migration');
select extensions.ok((select identities_md5 from v16a_before) = (select md5(string_agg(i::text, '|' order by i.id)) from private.cpsc_source_identities i)
  and (select aliases_md5 from v16a_before) = (select md5(string_agg(a::text, '|' order by a.id)) from private.cpsc_source_aliases a)
  and (select api_revisions_md5 from v16a_before) = (select md5(string_agg(r::text, '|' order by r.id)) from private.cpsc_api_revisions r)
  and (select notices_md5 from v16a_before) = (select md5(string_agg(n::text, '|' order by n.id)) from public.recall_notices n),
  'identities, aliases, API revisions, and notices unchanged by the migration');

-- Hash contract on real production payloads.
select extensions.is((select count(*) from public.recall_notices n
    where private.cpsc_payload_sha256_v1(n.raw_payload) is distinct from private.cpsc_canonical_json_sha256(n.raw_payload)),
  0::bigint, 'v1 hash equals the 16.12 hash on every production notice payload');
select extensions.ok((select count(*) from private.cpsc_identity_observations o
    join public.recall_notices n on n.external_id = o.upstream_api_id
      and private.cpsc_payload_recall_number(n.raw_payload) = o.official_recall_number
    where o.provenance like '%(stored notice)'
      and o.payload_hash = private.cpsc_payload_sha256_v1(n.raw_payload)) > 0
  and not exists (select 1 from private.cpsc_identity_observations o
    join public.recall_notices n on n.external_id = o.upstream_api_id
      and private.cpsc_payload_recall_number(n.raw_payload) = o.official_recall_number
    where o.provenance like '%(stored notice)'
      and o.payload_hash <> private.cpsc_payload_sha256_v1(n.raw_payload)),
  'v1 reproduces every hash the backfill recorded from stored notices');

-- Legacy treatment: the six production quarantines are hash-only and unsafe.
select extensions.is((select count(*) from private.cpsc_observation_payload_retention
    where resolution = 'quarantined' and payload_retention = 'legacy_hash_only'), 6::bigint,
  'six production quarantines are labelled legacy_hash_only');
select extensions.ok(not (private.cpsc_watermark_safety()->>'safe')::boolean, 'watermark safety is false before attachment');
select extensions.ok((select bool_and(exists (select 1 from jsonb_array_elements(private.cpsc_watermark_safety()->'unaccounted') u
    where u->>'apiId' = s.api and u->>'recallNumber' = s.num and u->>'payloadHash' = s.hash)) from v16a_six s)
  and jsonb_array_length(private.cpsc_watermark_safety()->'unaccounted') = 6,
  'unaccounted set is exactly the six known collisions');
select extensions.throws_ok($$select public.record_recall_source_sync_result('cpsc','success',
    '{"kind":"last_publish_date","value":"2026-12-31"}'::jsonb,null,'{}'::jsonb)$$,
  '23514', null, 'CPSC watermark advance is refused on production data');
select extensions.lives_ok($$select public.record_recall_source_sync_result('health_canada','success',
    (select watermark from private.recall_source_sync_state st join public.recall_sources s on s.id = st.source_id
      where s.source_key = 'health_canada'),null,'{}'::jsonb)$$,
  'Health Canada sync recording is unaffected');

-- Bounded attachment of the six captured payloads (rolled back).
create temporary table v16a_attach on commit drop as select $attach${
  "attachmentVersion": "phase-16.16a-captured-payload-attachment-v1",
  "apiRoot": "https://www.saferproducts.gov/RestWebServices/Recall",
  "captureSha256": "c4b43808804c376ec7d35b70230a23c8b3e8061cf8c44c8e25a7f904ff3b4bea",
  "capturedAtUtc": "2026-09-26T09:06:13.773Z",
  "derivedFrom": {
    "capture": "docs/phase-16-14-cpsc-fresh-capture.json",
    "recordedHashes": "docs/phase-16-15-backfill-manifest.json",
    "quarantines": "docs/phase-16-15-backfill-execution.json",
    "hashContract": "cpsc-canonical-json-sha256/v1"
  },
  "items": [
    {
      "apiId": "10969",
      "recallNumber": "26749",
      "payloadSha256": "1316efd47ec33bf7fc3029e985bd6d1049efbf4bcf450e3ea4599bef2aa7e23a",
      "payload": {
        "RecallID": 10969,
        "RecallNumber": "26749",
        "RecallDate": "2026-09-10T00:00:00",
        "Description": "This recall involves Victgoal-branded bicycle helmets. The red helmets were sold in size small (S), fitting a head circumference of about 19.68 to 21.25 inches. The helmets have red padding, black straps with a silver reflective pattern in the center, a black and red buckle and a black fit-adjusting knob at the back. Only helmets manufactured in November 2025 are included in this recall. \"Model HT-006,\" \"Production: 2025/11\" and \"Ref/Lot# 2025A1101\" are printed on a label on the inside of the helmet. \"Victgoal\" is printed on the product packing bag.",
        "URL": "https://cpsc.gov/Recalls/2026/Victgoal-Recalls-Bicycle-Helmets-Due-to-Risk-of-Serious-Injury-or-Death-from-Head-Injury-Violate-Mandatory-Standard-for-Bicycle-Helmets",
        "Title": "Victgoal Recalls Bicycle Helmets Due to Risk of Serious Injury or Death from Head Injury; Violate Mandatory Standard for Bicycle Helmets",
        "ConsumerContact": "Victgoal by email at walmart@victgoal.com.",
        "LastPublishDate": "2026-09-10T00:00:00",
        "Products": [
          {
            "Name": "Victgoal Children’s Bike Helmets",
            "Description": "",
            "Model": "",
            "Type": "Headgear or Helmets",
            "CategoryID": "1342",
            "NumberOfUnits": "About 40"
          }
        ],
        "Inconjunctions": [],
        "Images": [
          {
            "URL": "https://www.cpsc.gov/s3fs-public/victgoal1_0.jpg",
            "Caption": "Recalled Victgoal Children's Bike Helmet"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/victgoal2_0.png",
            "Caption": "Ref/Lot# 2025A1101' and \"Production: 2025/11\" are printed on a label on the inside of the recalled Victgoal children's helmet"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/victgoal3_0.jpg",
            "Caption": "\"Model HT-006\" is printed on a label on the inside of the recalled Victgoal children's helmet"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/victgoal4_0.jpg",
            "Caption": "Recalled Victgoal Children's Bike Helmet – packaging bag"
          }
        ],
        "Injuries": [
          {
            "Name": "None reported."
          }
        ],
        "Manufacturers": [
          {
            "Name": "Dongguan Hongtu Sports Goods Co. Ltd., of China",
            "CompanyID": ""
          }
        ],
        "Retailers": [
          {
            "Name": "Sold Online At:\nWalmart.com from March 2026 through June 2026 for between $22 and $36.",
            "CompanyID": ""
          }
        ],
        "Importers": [
          {
            "Name": "Victgoal, of China",
            "CompanyID": ""
          }
        ],
        "Distributors": [],
        "SoldAtLabel": null,
        "ManufacturerCountries": [
          {
            "Country": "China"
          }
        ],
        "ProductUPCs": [],
        "Hazards": [
          {
            "Name": "The recalled helmets violate the mandatory safety standard for bicycle helmets because the helmets do not comply with the retention system, positional stability and certification requirements. The helmets can fail to protect the user in the event of a crash, posing a serious risk of injury or death due to head injury.",
            "HazardType": "",
            "HazardTypeID": ""
          }
        ],
        "Remedies": [
          {
            "Name": "Consumers should stop using the recalled helmets immediately and contact Victgoal for a full refund. Consumers will be asked to destroy the helmets by cutting the straps and then sending a photo of the destroyed product, showing the helmet’s production date to walmart@victgoal.com. Consumers should then dispose of the recalled product."
          }
        ],
        "RemedyOptions": [
          {
            "Option": "Refund"
          }
        ]
      }
    },
    {
      "apiId": "10965",
      "recallNumber": "26753",
      "payloadSha256": "316823508cb771a7d86efaffbf04b8cc678703d59c34ae78ab29e5a594d18de0",
      "payload": {
        "RecallID": 10965,
        "RecallNumber": "26753",
        "RecallDate": "2026-09-10T00:00:00",
        "Description": "This recall involves the Lontcs Busy Board toys. The toys consist of a wood board and metal handle with multiple attached components including a black plastic buckle with cream colored straps; a brown zipper; a metal latch; a caster wheel; a white doorbell; a lock with keys; a music box with crank; a zig zag duck puzzle; an abacus with three rows of white; red and tan beads; and a white fidget spinner.",
        "URL": "https://cpsc.gov/Recalls/2026/SQT-Recalls-Lontcs-Busy-Boards-Due-to-Risk-of-Serious-Injury-from-Lead-Poisoning-Violate-Federal-Lead-Paint-Ban",
        "Title": "SQT Recalls Lontcs Busy Boards Due to Risk of Serious Injury from Lead Poisoning; Violate Federal Lead Paint Ban",
        "ConsumerContact": "SQT by email at Lontcs@163.com",
        "LastPublishDate": "2026-09-10T00:00:00",
        "Products": [
          {
            "Name": "Lontcs Busy Board",
            "Description": "",
            "Model": "",
            "Type": "Toy Miscellaneous",
            "CategoryID": "2198",
            "NumberOfUnits": "About 1,835"
          }
        ],
        "Inconjunctions": [],
        "Images": [
          {
            "URL": "https://www.cpsc.gov/s3fs-public/SQT1.png?VersionId=d9xWpvX_nU8QpaVc6XM_d8xH2XNzINMe",
            "Caption": "Recalled Lontcs Busy Board Toy"
          }
        ],
        "Injuries": [
          {
            "Name": "None reported"
          }
        ],
        "Manufacturers": [
          {
            "Name": "Xianyouxianlichengshaungqiaotouqichemeirongdian (Xianyou County Licheng Shuangqiaotou Auto Beauty Shop), dba SQT LLC, of China",
            "CompanyID": ""
          }
        ],
        "Retailers": [
          {
            "Name": "Sold Online At:\nAmazon.com from May 2024 through July 2026 for about $31.",
            "CompanyID": ""
          }
        ],
        "Importers": [],
        "Distributors": [],
        "SoldAtLabel": null,
        "ManufacturerCountries": [
          {
            "Country": "China"
          }
        ],
        "ProductUPCs": [],
        "Hazards": [
          {
            "Name": "The toys’ zipper contains levels of lead that exceed the standard set in the federal lead paint ban. Lead is toxic if ingested by young children and can cause adverse health issues.",
            "HazardType": "",
            "HazardTypeID": ""
          }
        ],
        "Remedies": [
          {
            "Name": "Consumers should stop using the busy boards immediately and contact SQT for a full refund. Consumers will be asked to destroy the toys by unscrewing its components, write in permanent marker “RECALLED” on the board, and send a photo of the destroyed toy to Lontcs@163.com. Consumers should then dispose of the destroyed product."
          }
        ],
        "RemedyOptions": [
          {
            "Option": "Refund"
          }
        ]
      }
    },
    {
      "apiId": "10967",
      "recallNumber": "26754",
      "payloadSha256": "5af2405f874ee90f9819eca708f6be60123abee3566bcdcd87b4f75df4f2e104",
      "payload": {
        "RecallID": 10967,
        "RecallNumber": "26754",
        "RecallDate": "2026-09-10T00:00:00",
        "Description": "This recall involves Wantefully 2 in 1 Hair Dryer & Styler, One Step Hair Dryer Brush Straightner, and the Negative Ion Electric Hot Air Blow Dryer Comb, model number XR-8801. The hair dryers are black hot air dryer paddle brushes with a striped pink design and brush bristles. There are three heat settings on the hair dryers. XRUI and the model name XR-8801 are printed on the top of the product packaging.",
        "URL": "https://cpsc.gov/Recalls/2026/Guang-Zhou-Recalls-Wantefully-Hair-Dryer-Brushes-Due-to-Risk-of-Serious-Injury-or-Death-from-Electrocution-Shock-and-Burn-Hazards-Violate-Federal-Regulations",
        "Title": "Guang Zhou Recalls Wantefully Hair Dryer Brushes Due to Risk of Serious Injury or Death from Electrocution, Shock and Burn Hazards; Violate Federal Regulations",
        "ConsumerContact": "Guang Zhou at wantefully@163.com.",
        "LastPublishDate": "2026-09-10T00:00:00",
        "Products": [
          {
            "Name": "Wantefully Hair Dryer Brushes",
            "Description": "",
            "Model": "",
            "Type": "Hair Dryers",
            "CategoryID": "1982",
            "NumberOfUnits": "About 2,295"
          }
        ],
        "Inconjunctions": [],
        "Images": [
          {
            "URL": "https://www.cpsc.gov/s3fs-public/guang1.gif?VersionId=IPYabnv4LtvKTkZhx2BoyjhgYZ4p8b1C",
            "Caption": "Recalled Wantefully Hair Dryer and Blow Dryer Brush"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/guang2.gif?VersionId=syW61Hsb5Wcoj2OG_ZXjqCQa60qQnJDG",
            "Caption": "Recalled Wantefully Hair Dryer and Blow Dryer Brush"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/guang3.gif?VersionId=qM6jcx1Q.34r3NsbG4hIyeOOgNIHihZN",
            "Caption": "Recalled Wantefully Hair Dryer and Blow Dryer Brush"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/guang4.gif?VersionId=Hk6fmFiACPoym4_JrzXQ8KPra.G2xdVW",
            "Caption": "Recalled Wantefully Hair Dryer and Blow Dryer Brush – Product Packaging"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/guang5.gif?VersionId=nioUsdizjwyhbNWEX8h9BbeEA0Aqaf7k",
            "Caption": "Product Packaging Label with Model Number"
          }
        ],
        "Injuries": [
          {
            "Name": "There has been one report of the hair dryer overheating and melting. No injuries have been reported."
          }
        ],
        "Manufacturers": [],
        "Retailers": [
          {
            "Name": "Sold Online At:\nAmazon.com from February 2026 through March 2026 for about $30.",
            "CompanyID": ""
          }
        ],
        "Importers": [],
        "Distributors": [
          {
            "Name": "Guang Zhou Shi Wan Te Fu Ke Ji You Xian Gong Si, dba Wantefully, of China",
            "CompanyID": ""
          }
        ],
        "SoldAtLabel": null,
        "ManufacturerCountries": [
          {
            "Country": "China"
          }
        ],
        "ProductUPCs": [],
        "Hazards": [
          {
            "Name": "The recalled hair dryer brushes are in violation of federal regulations for hair dryers as they lack an integrated immersion protection device, which presents a substantial product hazard to consumers and  the risk of death or serious injury from electrocution or shock if the hair dryers fall into water while plugged in. In addition, the recalled hair dryer brushes can overheat, posing a burn hazard.",
            "HazardType": "",
            "HazardTypeID": ""
          }
        ],
        "Remedies": [
          {
            "Name": "Consumers should unplug and stop using the recalled hair dryers immediately and contact Guang Zhou to receive a full refund. Consumers will be asked to cut the power cord and provide a photo of the destroyed product to wantefully@163.com."
          }
        ],
        "RemedyOptions": [
          {
            "Option": "Refund"
          }
        ]
      }
    },
    {
      "apiId": "10968",
      "recallNumber": "26756",
      "payloadSha256": "a300928462e2324ed88b30891146b0e8cd23a9417675a480d86dd20847b09cf1",
      "payload": {
        "RecallID": 10968,
        "RecallNumber": "26756",
        "RecallDate": "2026-09-10T00:00:00",
        "Description": "This recall involves freestanding AGA Elise and Mercury Series Dual Fuel Ranges, in 36- and 48-inch widths and freestanding La Cornue CornuFé Series Dual Fuel Ranges in 36- and 43-inch widths manufactured between March 19, 2025 and July 24, 2026. All units have gas surface burners, set for Natural or LP gas, with one to three electric ovens depending on size.  The products are sold in stainless steel, white and 13 other colors, which can be found at www.agarangeusa.com and www.lacornueusa.com. All colors, trim options and gas types (Natural or LP) are included.  The serial number is on the rating plate, which is located on the bottom panel of the unit under the storage drawer.",
        "URL": "https://cpsc.gov/Recalls/2026/Dual-Fuel-Ranges-Recalled-Due-to-Risk-of-Serious-Injury-or-Death-from-Fire-or-Explosion-Hazards-Manufactured-by-AGA-Rangemaster",
        "Title": "Dual Fuel Ranges Recalled Due to Risk of Serious Injury or Death from Fire or Explosion Hazards; Manufactured by AGA Rangemaster",
        "ConsumerContact": "AGA Rangemaster recall line toll-free at 888-257-7912 from 8 a.m. to 8 p.m. ET Monday through Friday, online at  www.agarangeusa/testcap-recall  or www.lacornueusa/testcap-recall and click on \"Recall Information\" at the bottom of the page for more information.",
        "LastPublishDate": "2026-09-10T00:00:00",
        "Products": [
          {
            "Name": "AGA Elise and Mercury Series Freestanding Dual Fuel Ranges and La Cornue CornuFé 90 and CornuFé 110 Series Freestanding Dual Fuel Ranges",
            "Description": "",
            "Model": "",
            "Type": "Gas Ranges (With Ovens)",
            "CategoryID": "975",
            "NumberOfUnits": "About 3,992 (In addition, about 336 were sold in Canada)"
          }
        ],
        "Inconjunctions": [
          {
            "URL": "https://recalls-rappels.canada.ca/en/alert-recall/aga-and-cornue-freestanding-dual-fuel-ranges-recalled-due-fire-hazard"
          }
        ],
        "Images": [
          {
            "URL": "https://www.cpsc.gov/s3fs-public/dual1.png?VersionId=8m0SZNGo_hKLAVVy12xNOnOVTK53eQHs",
            "Caption": "Recalled AGA Elise Freestanding Dual Fuel Range- Model AEL361DF"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/dual2.png?VersionId=BwwSOH6YMvlZ_Aq2wvhhTGOc7AoSUcWJ",
            "Caption": "Recalled AGA Mercury Freestanding Dual Fuel Range- Model AMC36DF "
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/dual3.png?VersionId=N8U2HDW8K0BuqRELbgyp47z2aMXrMq_P",
            "Caption": "Recalled AGA Mercury Freestanding Dual Fuel Range- Model AMC48DF"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/dual4.png?VersionId=ar7MoIBnUUk1TZnQoh8XHMTlIW0s2V.D",
            "Caption": "Recalled AGA Mercury Freestanding Dual Fuel Range- Model AMC48DF"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/dual5.png?VersionId=pQnAWBbSZ3Y4MMC8IQrchI4RcpbpRwup",
            "Caption": "Recalled La Cornue CornuFé 90 Dual Fuel Range Model- LAC9"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/dual6.png?VersionId=4q6vpUj9ZTDAOxcYedmpDF1RO0rKjRcH",
            "Caption": "Recalled La Cornue CornuFé 110 Dual Fuel Range Model- LAC1"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/dual7.png?VersionId=QfKdQXxONHq_oV359BLMFvG5nccHG2bk",
            "Caption": "Consumers can continue to use the electric oven sections indicated by the green checks but must shut off the gas supply valve which will prevent usage of the gas surface burners, indicated by the red X’s.  "
          }
        ],
        "Injuries": [
          {
            "Name": "None reported."
          }
        ],
        "Manufacturers": [
          {
            "Name": "AGA Rangemaster Limited, of United Kingdom",
            "CompanyID": ""
          }
        ],
        "Retailers": [
          {
            "Name": "Sold At:\nAuthorized appliance dealers nationwide from March 2025 through July 2026 for about $6,000 to $20,000.",
            "CompanyID": ""
          }
        ],
        "Importers": [],
        "Distributors": [],
        "SoldAtLabel": null,
        "ManufacturerCountries": [
          {
            "Country": "United Kingdom"
          }
        ],
        "ProductUPCs": [],
        "Hazards": [
          {
            "Name": "Dual Fuel Ranges with a missing cap from the gas test port can cause a gas leak,​ posing a risk of serious injury or death from fire or explosion hazards.",
            "HazardType": "",
            "HazardTypeID": ""
          }
        ],
        "Remedies": [
          {
            "Name": "Consumers should shut off the gas supply to avoid the risk of gas leak immediately and contact AGA Rangemaster. Consumers should promptly determine if their range is subject to recall by locating the model/serial number on the rating plate (on the bottom panel under the storage drawer) and visiting the Recall webpage at www.lacornueusa.com/testcap-recall or  www.agarangeusa.com/testcap-recall. If subject to the recall, consumers should contact AGA Rangemaster for a free inspection and repair by a certified technician. Consumers can continue to use only the electric oven sections of the range. The gas surface burners cannot be used."
          }
        ],
        "RemedyOptions": [
          {
            "Option": "Repair"
          }
        ]
      }
    },
    {
      "apiId": "10966",
      "recallNumber": "26763",
      "payloadSha256": "2ead4847dfed00d4d1280ccfc6493a1fe176dbb6a96c285faef0736b6e440117",
      "payload": {
        "RecallID": 10966,
        "RecallNumber": "26763",
        "RecallDate": "2026-09-10T00:00:00",
        "Description": "This recall involves 2025 and 2026 Triumph TF450 models Closed Course Competition Motorcycles. The motorcycles have a Jet Black/Pure White color scheme. Affected models are TF450-C, TF450-E, TF450-X and TF450RC Edition. The range of affected Vehicle Identification Numbers (VIN) is XXXXXXXXXXXCD4981 to and including XXXXXXXXXXXCP1597. The VIN is located on the vehicle identification plate on the left side of the steering head. Consumers can check if their VIN is included in this recall at https://www.triumphmotorcycles.com/owners/recalls.",
        "URL": "https://cpsc.gov/Recalls/2026/Triumph-Motorcycles-Recalls-Closed-Course-Competition-Motorcycles-Due-to-Risk-of-Serious-Injury-or-Death-from-Crash-Hazard",
        "Title": "Triumph Motorcycles Recalls Closed Course Competition Motorcycles Due to Risk of Serious Injury or Death from Crash Hazard",
        "ConsumerContact": "Triumph Motorcycles toll-free at 888-284-6288 from 8:30 a.m. to 6 p.m. ET Monday through Friday, email at tma.aftersales@triumphmotorcycles.com or online at https://www.triumphmotorcycles.com/owners/recalls or www.triumphmotorcycles.com and click “Owners” at the top of the page, then click \"Recalls\" for more information.",
        "LastPublishDate": "2026-09-10T00:00:00",
        "Products": [
          {
            "Name": "2025 and 2026 Triumph TF450 models Closed Course Competition Motorcycles",
            "Description": "",
            "Model": "",
            "Type": "Motorcycles/Dirt Bikes (Off-Road) & Accessories",
            "CategoryID": "2049",
            "NumberOfUnits": "About 1,560 (In addition, about 171 were sold in Canada)"
          }
        ],
        "Inconjunctions": [
          {
            "URL": "https://wwwapps.tc.gc.ca/Saf-Sec-Sur/7/VRDB-BDRV/search-recherche/detail.aspx?lang=eng&rn=2026378"
          }
        ],
        "Images": [
          {
            "URL": "https://www.cpsc.gov/s3fs-public/triumph1.png?VersionId=2heZTaR9AWOD.ivzUP_FbalRUuVyJNbk",
            "Caption": "Recalled 2025/2026 Triumph TF450 model Closed Course Competition Motorcycle"
          }
        ],
        "Injuries": [
          {
            "Name": "The firm has received 12 reports of a seized or sticking exhaust rocker shaft or damage to the exhaust valves that will result in a progressive decrease in engine performance. One injury, including a broken bone, has been reported."
          }
        ],
        "Manufacturers": [],
        "Retailers": [
          {
            "Name": "Sold At:\nAuthorized Triumph Motorcycle Dealers from January 2025 through July 2026 for between $10,000 and $15,000.",
            "CompanyID": ""
          }
        ],
        "Importers": [
          {
            "Name": "Triumph Motorcycles America Ltd., of Atlanta, Georgia",
            "CompanyID": ""
          }
        ],
        "Distributors": [],
        "SoldAtLabel": null,
        "ManufacturerCountries": [
          {
            "Country": "Thailand"
          }
        ],
        "ProductUPCs": [],
        "Hazards": [
          {
            "Name": "The engine rocker arm on the recalled motorcycles can seize or stick and the exhaust valves can remain open or break, posing a risk of serious injury or death from a crash hazard.",
            "HazardType": "",
            "HazardTypeID": ""
          }
        ],
        "Remedies": [
          {
            "Name": "Consumers should stop using 2025 and 2026 Triumph TF450 models Closed Course Competition Motorcycles immediately and contact Triumph Motorcycles for a free repair. Consumers can check if their VIN is included in this recall at https://www.triumphmotorcycles.com/owners/recalls. Consumers with recalled motorcycles should contact their local authorized Triumph Motorcycle dealer who will inspect the engine and replace the cylinder head free of charge."
          }
        ],
        "RemedyOptions": [
          {
            "Option": "Repair"
          }
        ]
      }
    },
    {
      "apiId": "10970",
      "recallNumber": "26766",
      "payloadSha256": "b4a8d7501f9a5ccd37fc2cfa74429a1a02a01134df7eb234aba23d7a44000731",
      "payload": {
        "RecallID": 10970,
        "RecallNumber": "26766",
        "RecallDate": "2026-09-10T00:00:00",
        "Description": "This recall expansion involves ZMC Group battery-operated light-up toys including a Mexican flag theme foam stick, a Unicorn headband, assorted colors and transparent jelly rings and heart shaped balloon flowers. Product Name  Item # 19.4\" Mexican Flag Theme Light Up Stick SS041-M Light-Up Unicorn Headband G02-UN Light-Up Assorted Colors Jelly Rings PS270 Light-Up Transparent Jelly Rings PS271 Light-Up Heart Balloon Flower 777-1 Packaging for the products has a label with the item number, identification of the distributor, place of manufacture, production date and batch number.",
        "URL": "https://cpsc.gov/Recalls/2026/ZMC-Group-Expands-Recall-of-Light-Up-Childrens-Toys-Due-to-Risk-of-Serious-Injury-or-Death-from-Battery-Ingestion-Violate-Mandatory-Standard-for-Toys",
        "Title": "ZMC Group Expands Recall of Light-Up Children’s Toys Due to Risk of Serious Injury or Death from Battery Ingestion; Violate Mandatory Standard for Toys",
        "ConsumerContact": "Email ZMC Group at recallzmctoy@gmail.com.",
        "LastPublishDate": "2026-09-10T00:00:00",
        "Products": [
          {
            "Name": "Light-Up Children’s Toys",
            "Description": "",
            "Model": "",
            "Type": "Toys",
            "CategoryID": "1386",
            "NumberOfUnits": "About 245,124 (ZMC Group previously recalled 124,560 battery-operated light up toys on May 07, 2026, which are included in the total of 245,124)"
          }
        ],
        "Inconjunctions": [],
        "Images": [
          {
            "URL": "https://www.cpsc.gov/s3fs-public/ZMC1.png?VersionId=jKsiSHQMIZXrlVmSuZizG0Mt2h61uwne",
            "Caption": "Recalled Light‑Up Foam Stick (Item No. SS041‑M) – Model Wrapped with Mexican Flag Design"
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/ZMC2.png?VersionId=q88gFM.RHst5Ga2pNazkmB1KXcFNAt9v",
            "Caption": "Recalled Light‑Up Foam Stick (Item No. SS041‑M) – End of stick showing accessible button cell batteries."
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/ZMC3.png?VersionId=WBISQGJFFAM2VVTgI7wB8ZSs0Kj0tqcj",
            "Caption": "Recalled Light‑Up Foam Stick (Item No. SS041‑M) – Labeling area located along the side of the stick."
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/ZMC4.png?VersionId=FTtnT9B2oTttoo5qoooR7SnFooSFimnt",
            "Caption": "Recalled light-up unicorn headband (Item No. G02-UN) – Headband and close up showing accessible button cell batteries."
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/ZMC5.png?VersionId=ZO_V5Gl9CAasgxomIqoYzqgUVox6fx0w",
            "Caption": "Recalled light-up assorted colors jelly rings (Item No. PS270) – Ring and close up showing accessible button cell batteries."
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/ZMC6.png?VersionId=e.1JJjhZ3Emqabi_oh4PztVjfBLOlaMN",
            "Caption": "Recalled light-up transparent jelly rings (Item No. PS271) – Ring and close up showing accessible button cell batteries."
          },
          {
            "URL": "https://www.cpsc.gov/s3fs-public/ZMC7.png?VersionId=i_wwYh1MUflfft7.dzesFSaj1NlwqT0H",
            "Caption": "Recalled light-up heart balloon flower (Item No. 777-1) – Wand and close up showing accessible button cell batteries."
          }
        ],
        "Injuries": [
          {
            "Name": "None reported."
          }
        ],
        "Manufacturers": [],
        "Retailers": [
          {
            "Name": "Sold At:\nDiva at Heart, primarily in California, Texas, Oregon, Mississippi, and Arizona, and various distributors and retail stores and online at https://www.divaatheartsj.com/ from October 2018 through July 2026.",
            "CompanyID": ""
          }
        ],
        "Importers": [
          {
            "Name": "ZMC Group Inc., of Los Angeles, California",
            "CompanyID": ""
          }
        ],
        "Distributors": [],
        "SoldAtLabel": null,
        "ManufacturerCountries": [
          {
            "Country": "China"
          }
        ],
        "ProductUPCs": [],
        "Hazards": [
          {
            "Name": "The recalled light-up toys violate the mandatory safety standard for children’s toys because the toys contain button cell batteries that can be easily accessed by children. If button cell or coin batteries are swallowed, the ingested batteries can cause serious injuries, including internal chemical burns, and death.",
            "HazardType": "",
            "HazardTypeID": ""
          }
        ],
        "Remedies": [
          {
            "Name": "Consumers should stop using the toys immediately, take them away from children and contact ZMC Group for a full refund. Consumers will be asked to remove the batteries, write “RECALLED” or a large “X” on the product with a permanent marker and submit a photo of the disposed product to recallzmctoy@gmail.com.   \n\nNote: Button cell batteries are hazardous. Batteries should be disposed of or recycled by following local hazardous waste procedures."
          }
        ],
        "RemedyOptions": [
          {
            "Option": "Refund"
          }
        ]
      }
    }
  ]
}
$attach$::jsonb as doc;
select extensions.is((private.cpsc_attach_captured_payloads((select doc from v16a_attach), false)->>'wouldAttach')::int, 6,
  'attachment dry run matches all six production quarantines');
select extensions.is((select count(*) from private.cpsc_observation_payloads), 0::bigint, 'dry run stores nothing');
select extensions.is((private.cpsc_attach_captured_payloads((select doc from v16a_attach), true)->>'attached')::int, 6,
  'attachment attaches six hash-verified payloads');
select extensions.is((private.cpsc_attach_captured_payloads((select doc from v16a_attach), true)->>'alreadyRetained')::int, 6,
  'attachment is idempotent');
select extensions.ok((private.cpsc_watermark_safety()->>'safe')::boolean, 'watermark safety holds after attachment');
select extensions.ok(e->'sourceRevision'->'payload' = item->'payload'
    and (e->'sourceRevision'->>'hashVerified')::boolean and e->>'payloadRetention' = 'retained'
    and exists (select 1 from jsonb_array_elements(e->'conflictingAliases') a
      where a->>'aliasKind' = 'api_id' and a->>'aliasValue' = item->>'apiId'
        and a->>'officialRecallNumber' <> item->>'recallNumber'),
  format('packet for %s carries the exact payload and the conflicting identity', item->>'recallNumber'))
  from v16a_attach, jsonb_array_elements(doc->'items') item,
    lateral (select private.cpsc_quarantine_evidence(o.id) e from private.cpsc_identity_observations o
      where o.resolution = 'quarantined' and o.upstream_api_id = item->>'apiId'
        and o.official_recall_number = item->>'recallNumber') packet;
select extensions.lives_ok($$select public.record_recall_source_sync_result('cpsc','success',
    '{"kind":"last_publish_date","value":"2026-12-31"}'::jsonb,null,'{}'::jsonb)$$,
  'CPSC watermark may advance once all quarantines are retained (rolled back)');
select extensions.ok((select count(*) from private.cpsc_identity_observations) = (select observations from v16a_before)
  and (select count(*) from private.cpsc_identity_reconciliations) = 0
  and (select count(*) from private.recall_scope_criteria_v2) = 0
  and (select historical_digest from v16a_before)
    = private.cpsc_historical_rows_digest((select id from public.recall_sources where source_key = 'cpsc')),
  'no observation, reconciliation, criterion, or historical row changed');

select * from extensions.finish();
rollback;
