#!/usr/bin/env python3
"""Generate the TS entity table so the Deno extractor matches Python's html.unescape.

Development-time only: the production extractor never runs Python.
"""

import html
import json
from html.entities import html5
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / "supabase/functions/_shared/cpsc/htmlEntities.ts"

body = f"""// Generated by scripts/generate-cpsc-html-entities.py from Python's html.entities.
// The CPSC extractor decodes character references exactly like html.unescape.
export const HTML5_ENTITIES: Readonly<Record<string, string>> = JSON.parse(
  {json.dumps(json.dumps(html5, ensure_ascii=True, sort_keys=True, separators=(",", ":")))},
);

export const INVALID_CHARREFS: Readonly<Record<number, string>> = JSON.parse(
  {json.dumps(json.dumps({str(k): v for k, v in html._invalid_charrefs.items()}, ensure_ascii=True, sort_keys=True, separators=(",", ":")))},
);

export const INVALID_CODEPOINTS: ReadonlySet<number> = new Set(
  {json.dumps(sorted(html._invalid_codepoints), separators=(", ", ":"))},
);
"""
OUTPUT.write_text(body)
print(OUTPUT)
